<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="9" passed="1" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-31T15:43:42 IST" name="Suite" finished-at="2023-12-31T15:44:24 IST" duration-ms="41936">
    <groups>
      <group name="ErrorHandling">
        <method signature="errorValidations.loginErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" name="loginErrorCheck" class="shoppingsite.tests.errorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="purchaseorder">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" name="SubmitOrder" class="shoppingsite.tests.SubmitOrderTest"/>
      </group> <!-- purchaseorder -->
    </groups>
    <test started-at="2023-12-31T15:43:42 IST" name="SubmitOrderTest" finished-at="2023-12-31T15:44:04 IST" duration-ms="21726">
      <class name="shoppingsite.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:43:42 IST" name="launchApp" finished-at="2023-12-31T15:43:47 IST" duration-ms="4648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:43:47 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-12-31T15:43:56 IST" duration-ms="9410" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ZARA COAT 3, passwd=Nuzvid@123, email=testpractice1@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:43:56 IST" name="closeDriver" finished-at="2023-12-31T15:43:57 IST" duration-ms="400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:43:57 IST" name="launchApp" finished-at="2023-12-31T15:44:02 IST" duration-ms="5399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:44:02 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-12-31T15:44:03 IST" duration-ms="1099" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ADIDAS ORIGINAL, passwd=Nuzvid@123, email=testpractice1@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[Element <button class="btn btn-custom"> is not clickable at point (1270,26) because another element <div class="ngx-spinner-overlay ng-tns-c31-1 ng-trigger ng-trigger-fadeIn ng-star-inserted ng-animating"> obscures it
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.2', java.version: '17.0.8'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [5359cf4c-da7b-4a71-9abd-63d788d4a8e0, clickElement {id=653707b8-607d-42b7-bdb5-e374687c0bf4}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 115.6.0, moz:accessibilityChecks: false, moz:buildID: 20231211164624, moz:debuggerAddress: 127.0.0.1:26985, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 23.1.0, moz:processID: 95629, moz:profile: /var/folders/6v/9lrvtpk51g3..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://127.0.0.1:26985/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Element: [[FirefoxDriver: firefox on mac (5359cf4c-da7b-4a71-9abd-63d788d4a8e0)] -> css selector: [routerlink="/dashboard/cart"]]
Session ID: 5359cf4c-da7b-4a71-9abd-63d788d4a8e0]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <button class="btn btn-custom"> is not clickable at point (1270,26) because another element <div class="ngx-spinner-overlay ng-tns-c31-1 ng-trigger ng-trigger-fadeIn ng-star-inserted ng-animating"> obscures it
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.2', java.version: '17.0.8'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [5359cf4c-da7b-4a71-9abd-63d788d4a8e0, clickElement {id=653707b8-607d-42b7-bdb5-e374687c0bf4}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 115.6.0, moz:accessibilityChecks: false, moz:buildID: 20231211164624, moz:debuggerAddress: 127.0.0.1:26985, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 23.1.0, moz:processID: 95629, moz:profile: /var/folders/6v/9lrvtpk51g3..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://127.0.0.1:26985/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Element: [[FirefoxDriver: firefox on mac (5359cf4c-da7b-4a71-9abd-63d788d4a8e0)] -> css selector: [routerlink="/dashboard/cart"]]
Session ID: 5359cf4c-da7b-4a71-9abd-63d788d4a8e0
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:224)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy16.click(Unknown Source)
at shoppingsite.AbstractComponents.AbstractComponents.gotocartpage(AbstractComponents.java:49)
at shoppingsite.tests.SubmitOrderTest.SubmitOrder(SubmitOrderTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:44:03 IST" name="closeDriver" finished-at="2023-12-31T15:44:04 IST" duration-ms="508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method signature="OrderHistoryTest(java.util.HashMap)[pri:0, instance:shoppingsite.tests.SubmitOrderTest@54422e18]" started-at="2023-12-31T15:44:04 IST" name="OrderHistoryTest" finished-at="2023-12-31T15:44:04 IST" depends-on-methods="shoppingsite.tests.SubmitOrderTest.SubmitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method shoppingsite.tests.SubmitOrderTest.OrderHistoryTest() on instance shoppingsite.tests.SubmitOrderTest@54422e18 depends on not successfully finished methods 
[shoppingsite.tests.SubmitOrderTest.SubmitOrder() on instance shoppingsite.tests.SubmitOrderTest@54422e18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method shoppingsite.tests.SubmitOrderTest.OrderHistoryTest() on instance shoppingsite.tests.SubmitOrderTest@54422e18 depends on not successfully finished methods 
[shoppingsite.tests.SubmitOrderTest.SubmitOrder() on instance shoppingsite.tests.SubmitOrderTest@54422e18]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- shoppingsite.tests.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2023-12-31T15:43:42 IST" name="errorValidations" finished-at="2023-12-31T15:44:24 IST" duration-ms="41936">
      <class name="shoppingsite.tests.errorValidations">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:43:42 IST" name="launchApp" finished-at="2023-12-31T15:43:47 IST" duration-ms="4692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="ProductNameErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:43:47 IST" name="ProductNameErrorCheck" finished-at="2023-12-31T15:44:03 IST" duration-ms="16032" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at shoppingsite.tests.errorValidations.ProductNameErrorCheck(errorValidations.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNameErrorCheck -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:03 IST" name="closeDriver" finished-at="2023-12-31T15:44:03 IST" duration-ms="389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:03 IST" name="launchApp" finished-at="2023-12-31T15:44:07 IST" duration-ms="4123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="loginErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:07 IST" name="loginErrorCheck" finished-at="2023-12-31T15:44:09 IST" duration-ms="1362" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Incorrect email or password.> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Incorrect email or password.> but was:<>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at shoppingsite.tests.errorValidations.loginErrorCheck(errorValidations.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorCheck -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:09 IST" name="closeDriver" finished-at="2023-12-31T15:44:09 IST" duration-ms="382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:09 IST" name="launchApp" finished-at="2023-12-31T15:44:15 IST" duration-ms="5609" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="loginErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:15 IST" name="loginErrorCheck" finished-at="2023-12-31T15:44:16 IST" duration-ms="1358" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Incorrect email or password.> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Incorrect email or password.> but was:<>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at shoppingsite.tests.errorValidations.loginErrorCheck(errorValidations.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorCheck -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:16 IST" name="closeDriver" finished-at="2023-12-31T15:44:16 IST" duration-ms="369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:16 IST" name="launchApp" finished-at="2023-12-31T15:44:22 IST" duration-ms="5511" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="loginErrorCheck()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:22 IST" name="loginErrorCheck" finished-at="2023-12-31T15:44:23 IST" duration-ms="1379" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Incorrect email or password.> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Incorrect email or password.> but was:<>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at shoppingsite.tests.errorValidations.loginErrorCheck(errorValidations.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorCheck -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:shoppingsite.tests.errorValidations@19932c16]" started-at="2023-12-31T15:44:24 IST" name="closeDriver" finished-at="2023-12-31T15:44:24 IST" duration-ms="378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- shoppingsite.tests.errorValidations -->
    </test> <!-- errorValidations -->
  </suite> <!-- Suite -->
</testng-results>
